//Launching Chrome Browser
function launchBrowser1()
{
    let browserName="chrome"
    if(browserName == "chrome")
    {
        console.log("Launched the browser: " +browserName)
    }
    else
    {
        console.log("launched different browser")
    }
}
launchBrowser1();
console.log("-----------")

//Launching Edge Browser
function launchBrowser2()
{
    let browserName="Edge"
    if(browserName == "chrome")
    {
        console.log("Launched the browser: " +browserName)
    }
    else
    {
        console.log("launched different browser")
    }
}
launchBrowser2();
console.log("-----------")




